[package]
name = "noir_bigcurve"
type = "lib"
authors = [""]
compiler_version = ">=0.32.0"

[dependencies]
bignum = {path = "../noir-bignum"}
# bignum = {tag = "v0.1", git = "https://github.com/zac-williamson/noir-bignum"}